version: '3.8'

services:

  app:
    build:
      context: ./challenge
      dockerfile: Dockerfile
    image: gcr.io/devfest22-challenges/options
    ports:
      - '1600:8000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 400M
