version: '3.8'

services:

  app:
    build: ./app
    ports:
      - '5000:5000'
    image: gcr.io/devfest22-challenges/world-cup
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
