version: '3.8'

services:

  server:
    build: .
    ports:
      - '1401:1337'
    image: gcr.io/devfest22-challenges/rop-it-off
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: socat - TCP4:localhost:1337 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
