version: '3.8'

services:

  server:
    build: .
    ports:
      - '1337:1337'
    # image: gcr.io/${PROJECT_ID}/rop-it-off
    healthcheck:
      test: socat - TCP4:localhost:1337 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
