version: '3.8'

services:

  server:
    build: .
    ports:
      - '1402:1337'
    image: gcr.io/devfest22-challenges/you-me-printf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
